######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 26 22:31:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += GUI_i7z.cpp
